### PR TITLE
Introduction to embedded Neo4j API based on Scala

### PR DESCRIPTION
**Pull request by brunokam**
The preview of the new Neo4j API has been released. Current implementation includes TCP server and get_model_nodes function.

### CODE REVIEW

**Comment by kudkudak** [comment]
This is a truly valiant effort, but I would be delighted to accept this pull request should it have more functionalities baked in in contrast to the currently presented state.

**Comment by kudkudak** [comment]
Also a performance comparision would be a truly great source of insight into the tradeoff between expected implementation time and performance gain we might be priviledged to experience.

**Comment by brunokam** [comment]
The server based on Python is still the main unit which processes database queries. Therefore, we are able to compare results quickly.

**Comment by kudkudak** [comment]
How is it going? Are we merging it in the nearest future?

**Comment by brunokam** [comment]
Hopefully next week.

**Pull request merged**
