### PR TITLE
Ocean don corleone

### PR DESCRIPTION
**Pull request by kudkudak**
- Few fixes
- Added parametrized running (much easier running option - already used with lionfish, will be used with kafka)

### CODE REVIEW

**Comment by kudkudak** [comment]
- Added experimentally spidercrab services to services that are passed config also by parameters.
- Fixed issue with node_id

**Comment by ktalik** [comment]
`get_your_node_id()` fails running:

```
Traceback (most recent call last):
  File "/home/konrad/workspace/ocean/ocean-git/graph_workers/spidercrab.py", line 749, in <module>
    master_sc = Spidercrab.create_master()
  File "/home/konrad/workspace/ocean/ocean-git/graph_workers/spidercrab.py", line 125, in create_master
    spidercrab_master = Spidercrab(**params)
  File "/home/konrad/workspace/ocean/ocean-git/graph_workers/spidercrab.py", line 74, in __init__
    self._init_config(master, config_file_name)
  File "/home/konrad/workspace/ocean/ocean-git/graph_workers/spidercrab.py", line 325, in _init_config
    enforce_running=False
  File "/home/konrad/workspace/ocean/ocean-git/graph_workers/../don_corleone/don_utils.py", line 100, in get_running_service
    return get_service(services, service_id = service_id, node_id=node_id,  service_name=service_name, service_config=service_config)
  File "/home/konrad/workspace/ocean/ocean-git/graph_workers/../don_corleone/don_utils.py", line 65, in get_service
    if node_id is not None and s[NODE_ID] != node_id:
KeyError: 'node_id'
```

You are accessing wrong dictionary (`s`). By the way change method name to `get_my_node_id()` or something similar, which is more adequate.

**Comment by kudkudak** [comment]
Your config.json is obsolete: please add "node_id"  field to config.json. I have renamed the method name, no code on ocean_don_corleone used get_your_node_id() yet.

**Comment by ktalik** [comment]
I have `"node_id"` all time.

**Comment by kudkudak** [comment]
get_my_node_id() was working corretcly, it was get_running_service failing for not running don corleone. Check now

**Pull request merged**
