### PR TITLE
Spidercrab

### PR DESCRIPTION
**Pull request by ktalik**
Finished synchronized database news fetchers (Spidercrab), that includes:
1. News fetchers as _graph workers_ that can work in a _distributed way_, that is in a master-slave communication model slave workers can work from anywhere (remotely) for one master that is managing a task list through the database (node relations). Every single worker can derive configuration from database or set its own config locally.
2. News text content extraction based on _boilerpipe_. _In future: image extraction_.
3. RSS feeds parsing in all popular versions (RSS 0.9x, RSS 1.0, RSS 2.0, _and in future: CDF, Atom 0.3, and Atom 1.0 feeds_)

### CODE REVIEW

**Comment by kudkudak** [comment]
Please write simple unit test (or if there is already let me know which file it is in) with prepared preloaded data for neo4j. It will make it easier to test pull request. Also maybe before accepting pull request write scripts for spidercrab_master and spidercrab_slave so I can test it with don corleone (again easier for me ;) )

**Comment by ktalik** [comment]
Simple test is located under `tests/spidercrab_correctnes_test.py`. There is a need to press Enter after restarting an Lionfish ODM server. If you need to automatize this, please do this yourself using Don Corleone magic stuff.

Spidercrab management instructions are now available on [wiki](https://github.com/bziiuj/ocean/wiki/Spidercrab) :)

**Comment by kudkudak** [comment]
Ok I will prepare automatic script and test spidercrab. One thing : how can I fetch newly added nodes ? (For tagging purposes) Ideally would be to push this to Kafka

**Comment by kudkudak** [comment]
There is an error : in config.json you should add separately spidercrab master and slave in config.json.  number of slaves has to be in config.json. I dont want to make big modifations to ur code and it is not compatible with don for now.

In principle you should have ["spidercrab_slave", ..] and ["spidercrab_master", ...] in config.json as separate entries. Both with local=true for now. 

Also: are you checking if id is duplicated and if it is yes how is it resolved?

**Comment by ktalik** [comment]
> One thing : how can I fetch newly added nodes ? (For tagging purposes) Ideally would be to push this to Kafka

I assume you ask how can you get them from database? When adding new `ContentSource` nodes with master (`./spidercrab_master.py -s ../data/my_source_filler`), every new node receives a `pending` relation, so you can get them like this: (assume there are no slaves)

``` Cypher
MATCH
        (crab:Spidercrab {worker_id: 'my_worker_id'})
        -[r:pending]->
        (source:ContentSource)
RETURN source
LIMIT 1
```

(of course your own `worker_id` and `LIMIT` values)

If you ask about queuing newly added news to be tagged, there is no such a functionality. I can implement this, just tell me how you see it. I suppose you want them to be added to Kafka. If yes, then this task depends on whole Kafka organisational stuff.

We should talk about Kafka stuff on the next meeting and think about some model of data/tasks flow, some scheme or organisational rules.

> There is an error : in config.json you should add separately spidercrab master and slave in config.json. number of slaves has to be in config.json.

It's not an error - it's a feature ^__^ Master and slave are usually sharing the same config (they are frankly the same program, but distributed).

**Number of slaves** (`-n NUMBER, --number=NUMBER`) is an _option_, not a _configuration_. The same are: 
- `-c CONFIG_FILE_NAME, --config=CONFIG_FILE_NAME`
- `-e EXPORT_FILE_NAME, --export-cs-to=EXPORT_FILE_NAME`
- `-s SOURCES_FILE_NAME, --sources-urls-file=SOURCES_FILE_NAME`

Options differ from configuration in this way, that they are usually changing from launch to launch. I other words, options are usually different for every run (Just like opening a file in an editor -- filename should not be in any configuration ;) - its an option (argument))

> Also: are you checking if id is duplicated and if it is yes how is it resolved?

If id is duplicated, script is not registering this Spidercrab master in database (becouse he is already registered) ;) (see `_check_and_register()` method inside `spidercrab.py`)

**Comment by ktalik** [comment]
Config has been divided to master and slave. Runtime options are now available in config.json. Please see the newest commit and consider merging.

I was unable to work with `run_node.py`. First I received an error:

```
./init.sh: line 3: /usr/local/bin/virtualenvwrapper.sh: Nie ma takiego pliku ani katalogu
```

Hence i changed line 3 to `source virtualenvwrapper.sh`, then it worked but still had an error:

```
ERROR: Environment 'ocean' does not exist. Create it with 'mkvirtualenv ocean'
```

Consider merging `spidercrab` to `dev` and  after this merge `dev` to `ocean_con_corleone`, where you should add proper Corleone-related funtionalities.

**Comment by kudkudak** [comment]
I have even mentioned it on our facebook page ;) We are working using virtualenv - this means you have to type workon ocean (and before that write mkvirtualenv ocean). Of course that assumes you have installed virtualenv (described on wiki paged)

**Comment by ktalik** [comment]
I know "we" are using virtualenv. But "we" are using virtualnev only on `ocean_don_corleone`-related things, which is your branch.

This branch is, in my opinion finished in view of tasks from last iteration (If the above issue is the only issue).

**Pull request merged**
