### PR TITLE
Ocean Don Corleone

### PR DESCRIPTION
**Pull request by kudkudak**
Created basic outline of Don Corleone. There is little work to do with backend and frontend is not existing yet.

### CODE REVIEW

**Comment by ktalik** [comment]
I have no objections. :ship: :shipit:

**Comment by kudkudak** [comment]
I have pushed another commit with backend core finished. I am pretty proud of that one! I think I will pull off frontend as well. Local feature might need to wait for better times. Peace ! :pear:

**Comment by snakoneczny** [comment]
Good job Staszek!

**Comment by kudkudak** [comment]
Thanks man I am really doing my best here. I think I should be able to finish off Don Corleone before our next meeting, which is quite exciting!

**Comment by brunokam** [comment]
I can't wait! #ocean

**Pull request merged**
