### PR TITLE
Lionfish

### PR DESCRIPTION
**Pull request by brunokam**
Lionfish has been enhanced with a multi-operation batch functionality.

### CODE REVIEW

**Comment by ktalik** [comment]
There is an essential bug in batch mode for get_by_uuid method. When receiving a results, they are not always in a proper order... This leads to ambiguity on the client side.

**Comment by brunokam** [comment]
@ktalik Yes, you're right. I've also noticed the problem this evening and I'll hopefully solve it in the next few days.

**Comment by brunokam** [comment]
I've already fixed the bug which is mentioned above.

**Comment by kudkudak** [comment]
Good job! You are a great asset in our team. Thank you

**Comment by brunokam** [comment]
Oh, it was a pleasure.

**Pull request merged**
