### PR TITLE
Spidercrab: i06t02, i06t03, i06t04, i06t07

### PR DESCRIPTION
**Pull request by ktalik**
- Description:
  - Integration with Ocean Don Corleone
    -  8b86f02 Merge integration fixes — Konrad Talik
    -  0800daa Spidercrab _check_and_pull_config() from Corleone
  - Integration with tagging module (database labels, ...?)
    - 54118fb NotYetTagged label for Content nodes
- Time: 3 h
  - Some minor delays related to `don_utils.py`

Merging this request would close issue #105.

### CODE REVIEW

**Comment by kudkudak** [comment]
Note: pass node_id to get_configuration and test if it works (use don on ocean-don.no-ip.biz)

**Comment by ktalik** [comment]
`node_id` is now passed to `get_running_service` and is working.

**Comment by ktalik** [comment]
Looping now works as described in 1bd2c1b.

**Comment by ktalik** [comment]
Add last fixes and improvements.

This pull request is ready to test and merge. It closes following tasks:
- i06t03: Spidercrab slave improvements (#103)
- i06t07: Spidercrab master improvements (#106)
- i06t02: Spidercrab system integration (#105)
- i06t04: Content sources database setup (#104)

Please comment if there is anything missing.

**Comment by ktalik** [comment]
Spidercrab is passing the test but I am thinking about more restrictive version of this test now.

**Pull request merged**
