### PR TITLE
Fixed non-passing test_4.py

### PR DESCRIPTION
**Pull request by kudkudak**
- Added don_utils API
- Fixed non passing test

### CODE REVIEW

**Comment by ktalik** [comment]
That's good, but what I was talking about were typos in `don_utils.py`. Take a look at them and better send a pull request from actual `dev` version since there was a `revert` performed on files you are editing and therefore are conflicts which makes this request unable to actomatically merge it.

**Comment by kudkudak** [comment]
Sorry I do not know revert mechanism and no idea what is going on - I think the revert was unnecessary I could have simply pushed 1 commit because it is one-liner error. I have got already one commit on ocean_don_corleone, could you please fix it so that I can merge from ocean_don_corleone?

**Comment by kudkudak** [comment]
Nvm I can merge it simply manually

**Comment by ktalik** [comment]
You are right. I just wanted to keep things _proper_ - code is unstable so there is no merge. But then I realised that it camed with more complexity and was unnecessary. The conclusion is to check code twice before accepting pull request.

**Comment by ktalik** [comment]
I know it's a  "jan test" but it should nevertheless work. After running `python2 jan_test_don_utils.py`:

```
sh: ./scripts/don_corleone_test.sh: Nie ma takiego pliku ani katalogu
```

_TYPOS HAPPNE_, but after searching I don't know which code it is in this case:

``` sh
$ git grep don_corleone_test.sh
don_corleone_client.py:    while config[MASTER_LOCAL] and os.system("./scripts/don_corleone_test.sh") != 0 and not terminated:
don_corleone_client.py:        if os.system("./scripts/don_corleone_test.sh") != 0:
don_utils.py:    if (config[MASTER_LOCAL] and os.system("./scripts/don_corleone_test.sh") != 0) or enforce_local:
don_utils.py:    if config[MASTER_LOCAL] and os.system("./scripts/don_corleone_test.sh") != 0:
tests/test_1.py:        assert(os.system("scripts/don_corleone_test.sh") != 0)
tests/test_3.py:        assert(os.system("scripts/don_corleone_test.sh") != 0)
tests/test_4.py:        assert(os.system("scripts/don_corleone_test.sh") != 0)
```

**Comment by ktalik** [comment]
OK. It works when running from parent directory `python2 tests/jan_test_don_utils.py` but anyway take a look at this.

**Pull request merged**
